title: Cyber Security | Learning 
#logo
description: Follow my learning and passion for Cyber Security
#show_downloads: true
jremote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
